apiVersion: apps/v1
kind: Deployment
metadata:
  name: podmortem-operator
  namespace: {{ .Values.namespace }}
  labels:
    app: podmortem-operator
    component: operator
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      app: podmortem-operator
  template:
    metadata:
      labels:
        app: podmortem-operator
        component: operator
    spec:
      serviceAccountName: podmortem-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: operator
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "podmortem-operator"
            - name: QUARKUS_REST_CLIENT_LOG_PARSER_URL
              value: "http://podmortem-log-parser-service.{{ .Values.namespace }}.svc.cluster.local:8080"
            - name: QUARKUS_REST_CLIENT_AI_INTERFACE_URL
              value: "http://podmortem-ai-interface-service.{{ .Values.namespace }}.svc.cluster.local:8080"
          resources: {{- toYaml .Values.operator.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: pattern-cache
              mountPath: /shared/patterns
      volumes:
        - name: tmp
          emptyDir: {}
        - name: pattern-cache
          persistentVolumeClaim:
            claimName: pattern-cache-pvc
      terminationGracePeriodSeconds: 60 