{{- if .Values.logParser.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podmortem-log-parser-service
  namespace: {{ .Values.namespace }}
  labels:
    app: podmortem-log-parser-service
spec:
  replicas: {{ .Values.logParser.replicaCount }}
  selector:
    matchLabels:
      app: podmortem-log-parser-service
  template:
    metadata:
      labels:
        app: podmortem-log-parser-service
    spec:
      containers:
        - name: log-parser
          image: "{{ .Values.logParser.image.repository }}:{{ .Values.logParser.image.tag }}"
          imagePullPolicy: {{ .Values.logParser.image.pullPolicy }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: pattern-cache
              mountPath: /shared/patterns
              readOnly: true
      volumes:
        - name: pattern-cache
          persistentVolumeClaim:
            claimName: pattern-cache-pvc
{{- end }} 