{{- if .Values.logParser.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: podmortem-log-parser-service
  namespace: {{ .Values.namespace }}
  labels:
    app: podmortem-log-parser-service
spec:
  selector:
    app: podmortem-log-parser-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
{{- end }} 